---
dist: xenial
sudo: required
language: python
python: '3.7'
branches:
  only:
    - master

env:
  - EL=6
  - EL=7

services:
  - docker

before_script:
  - cd ../
  - mv ansible-role-epel daixijun.epel
  - cd daixijun.epel

install:
  - pip install ansible molecule docker

script:
  - molecule test

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
