---
- name: Install epel-release
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Replace epel repo
  get_url:
    url: "{{ epel_repo_url }}"
    dest: /etc/yum.repos.d/epel.repo
    force: true
  when:
    - ansible_os_family == "RedHat"
    - epel_repo_replace|bool
